#!/usr/bin/env python3
"""
Zorynex bootstrap utility.

Initializes local development environment by:

- generating an Ed25519 signing key
- creating/upgrading the database schema
- writing a local .env configuration

Usage:

    python bootstrap.py
    python bootstrap.py --start

Use --start to automatically launch the API server after setup.
"""

from __future__ import annotations

import os
import secrets
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).parent


# ── Helpers ───────────────────────────────────────────────────────────────────

def _check(label: str) -> None:
    print(f"  ✓  {label}")


def _fail(label: str, detail: str) -> None:
    print(f"  ✗  {label}: {detail}", file=sys.stderr)
    sys.exit(1)


def _section(title: str) -> None:
    print(f"\n── {title} " + "─" * (54 - len(title)))


# ── Step 1: Generate signing key ──────────────────────────────────────────────

def generate_signing_key() -> tuple[str, str]:
    """Generate Ed25519 key pair. Returns (private_hex, key_id)."""
    try:
        from nacl.signing import SigningKey
    except ImportError:
        _fail("PyNaCl not installed", "pip install pynacl")

    sk      = SigningKey.generate()
    priv    = sk.encode().hex()
    key_id  = "env-" + sk.verify_key.encode().hex()[:16]
    return priv, key_id


# ── Step 2: Initialise database ───────────────────────────────────────────────

def init_database(db_path: str) -> None:
    """Create tables and run migrations."""
    sys.path.insert(0, str(ROOT))
    try:
        from provable_ai.storage import SQLiteStorage
        storage = SQLiteStorage(db_path=db_path)
        # Verify tables exist by running a quick check
        cur = storage.conn.cursor()
        cur.execute("SELECT count(*) FROM approved_models")
        storage.conn.close()
    except Exception as e:
        _fail("Database initialisation", str(e))


# ── Step 3: Write .env ───────────────────────────────────────────────────────

def write_env(
    signing_key:    str,
    db_path:        str,
    dev_api_key:    str,
    webhook_secret: str,
    env_path:       Path,
) -> None:
    content = textwrap.dedent(f"""\
        # Zorynex environment — generated by bootstrap.py
        # Source this before starting the server:
        #   source .env

        # ── Signing key ──────────────────────────────────────────────────────
        # Ed25519 private key (hex). Never commit this file.
        export ZORYNEX_SIGNING_KEY="{signing_key}"

        # ── API keys ─────────────────────────────────────────────────────────
        # Format: key:role,key:role  Roles: admin | system | auditor
        export ZORYNEX_API_KEYS="{dev_api_key}:admin"

        # ── Webhook ──────────────────────────────────────────────────────────
        # HMAC-SHA256 secret for inbound webhook verification
        export ZORYNEX_WEBHOOK_SECRET="{webhook_secret}"

        # ── Database ─────────────────────────────────────────────────────────
        export ZORYNEX_DB_PATH="{db_path}"
        export ZORYNEX_AUDIT_DB_PATH="zorynex_audit.db"
        export ZORYNEX_ANCHOR_DB_PATH="zorynex_anchors.db"
        export ZORYNEX_KEYREGISTRY_DB_PATH="zorynex_keys.db"
        export ZORYNEX_DRIFT_DB_PATH="zorynex_drift.db"

        # ── Environment ──────────────────────────────────────────────────────
        export ZORYNEX_ENV="development"
        export ZORYNEX_REQUIRE_TENANT="false"   # set to "true" in production
        export ZORYNEX_ANCHOR_RFC3161="false"   # set to "true" to enable FreeTSA

        # ── Server ───────────────────────────────────────────────────────────
        export ZORYNEX_PORT="8000"
        # export ZORYNEX_WORKERS="4"          # for production
        # export ZORYNEX_WEBHOOK_SECRET=""    # for inbound webhook HMAC
    """)

    env_path.write_text(content)


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(
        description="Zorynex first-run bootstrap",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""
          Examples:
            python bootstrap.py             # bootstrap only, print next steps
            python bootstrap.py --start     # bootstrap + start the server
        """),
    )
    parser.add_argument(
        "--start", action="store_true",
        help="After bootstrapping, automatically start the uvicorn server"
    )
    args = parser.parse_args()

    print()
    print("=" * 62)
    print("  Zorynex Bootstrap")
    print("=" * 62)

    # ── Config ────────────────────────────────────────────────────────────────
    db_path    = os.environ.get("ZORYNEX_DB_PATH", "provable_ai.db")
    dev_key    = "dev-key"
    env_path   = ROOT / ".env"

    # Warn if .env already exists
    if env_path.exists():
        print(f"\n  .env already exists at {env_path}")
        print()
        print("  WARNING: Generating a new signing key means:")
        print("  · Existing proofs remain valid (each proof embeds its own public key)")
        print("  · New proofs will use the new key (different key_id)")
        print("  · Old and new proofs can coexist and verify independently")
        print()
        ans = input("  Overwrite? This will generate a NEW signing key. [y/N] ").strip().lower()
        if ans != "y":
            print("  Aborted. Existing .env unchanged.")
            sys.exit(0)

    # ── Step 1: Signing key ───────────────────────────────────────────────────
    _section("Signing key")
    signing_key, key_id = generate_signing_key()
    _check(f"Ed25519 key generated  →  {key_id}")

    # ── Step 2: Database ──────────────────────────────────────────────────────
    _section("Database")
    os.environ["ZORYNEX_SIGNING_KEY"] = signing_key
    os.environ["ZORYNEX_DB_PATH"]     = db_path
    db_exists = Path(db_path).exists()
    init_database(db_path)
    if db_exists:
        _check(f"Existing database detected  →  {db_path}")
        _check("Schema migrations checked  →  up to date")
    else:
        _check(f"SQLite database initialised  →  {db_path}")
        _check("Schema migrations complete")

    # ── Step 3: .env file ─────────────────────────────────────────────────────
    _section("Environment file")
    webhook_secret = secrets.token_hex(32)
    write_env(signing_key, db_path, dev_key, webhook_secret, env_path)
    _check(f".env written  →  {env_path}")

    # ── Done ──────────────────────────────────────────────────────────────────
    print()
    print("=" * 62)
    print("  Bootstrap complete. Next steps:")
    print("=" * 62)
    print()
    print("  1. Load environment:")
    print("     source .env")
    print()
    print("  2. Start the server:")
    print("     uvicorn server.main:app --reload")
    print()
    print("  3. Open Swagger:")
    print("     http://127.0.0.1:8000/docs")
    print()
    print("  4. In Swagger → Authorize, enter:")
    print(f"     X-API-Key:    {dev_key}")
    print(f"     X-Tenant-Id:  default")
    print()
    print(f"  Signing key:  {key_id}")
    print(f"  Database:     {db_path}")
    print()
    print("  .env is in .gitignore — never commit it.")
    print("  Run this script again ONLY if you intentionally want to rotate signing keys.")
    print()
    print("  Verify exported proofs:")
    print("  python verify/verify_package.py <proof.json>")
    print("=" * 62)
    print()

    # ── Auto-start server if --start flag ─────────────────────────────────────
    if args.start:
        import subprocess
        env_file = env_path
        print("  Starting server…  (loading .env and launching uvicorn)")
        print()

        # Load .env into this process before exec
        if env_file.exists():
            for line in env_file.read_text().splitlines():
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, _, val = line.partition('=')
                    key = key.replace('export ', '').strip()
                    val = val.strip().strip('"')
                    os.environ[key] = val

        subprocess.run([
            sys.executable, "-m", "uvicorn",
            "server.main:app",
            "--reload",
            "--host", "127.0.0.1",
            "--port", os.environ.get("ZORYNEX_PORT", "8000"),
        ], check=False)


if __name__ == "__main__":
    main()