{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zorynex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zorynex.labels" . | nindent 4 }}
  annotations:
    # Never include this secret in helm diff output
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  ZORYNEX_API_KEYS: {{ .Values.secrets.apiKeys | quote }}
  {{- if .Values.secrets.signingKey }}
  ZORYNEX_SIGNING_KEY: {{ .Values.secrets.signingKey | quote }}
  {{- end }}
  {{- if .Values.secrets.webhookSecret }}
  ZORYNEX_WEBHOOK_SECRET: {{ .Values.secrets.webhookSecret | quote }}
  {{- end }}
{{- end }}
